name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to use Node.js 20

    - name: Set up Go
      uses: actions/setup-go@v4  # Updated to use Node.js 20
      with:
        go-version: 1.22.3

    - name: Install dependencies
      run: go mod tidy

    - name: Install golint
      run: |
        GO111MODULE=on go install golang.org/x/lint/golint@latest
        echo "${GOPATH}/bin" >> $GITHUB_PATH

    - name: Run go fmt
      run: go fmt ./...

    - name: Run golint
      run: golint ./...

    - name: Run go vet
      run: go vet ./...

    - name: Check for unused imports and variables
      run: go list ./... | xargs go vet -unusedresult
