name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.3

    - name: Install dependencies
      run: go mod tidy

    - name: Install golint
      run: go install golang.org/x/lint/golint@latest

    - name: Run go fmt
      run: go fmt ./...

    - name: Run golint
      run: go run golang.org/x/lint/golint ./...

    - name: Run go vet
      run: go vet ./...

    - name: Check for unused imports and variables
      run: go list ./... | xargs go vet -unusedresult
